services:
  mysql:
    container_name: mysql
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=restdb
      - MYSQL_USER=restadmin
      - MYSQL_PASSWORD=password
    expose:
      - 3306
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
  auth-server:
    container_name: auth-server
    image: spring-6-auth-server:0.0.1-SNAPSHOT
    expose:
      - 9000
    ports:
      - 9000:9000
  rest-mvc:
    container_name: rest-mvc
    image: spring-7-rest-mvc:0.0.1-SNAPSHOT
    expose:
      - 8081
    ports:
      - 8081:8081
    environment:
      - SPRING_PROFILES_ACTIVE=mysqllocal
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/restdb
      - SERVER_PORT=8081
      - SPRING_DOCKER_COMPOSE_ENABLED=false
    depends_on:
      - mysql
      - auth-server
  reactive-mongo:
    container_name: reactive-mongo
    image: reactive-mongo:0.0.1-SNAPSHOT
    expose:
      - 8083
    ports:
      - 8083:8083
    environment:
      - SFG_MONGOHOST=mongo
      - SERVER_PORT=8083
    depends_on:
      - auth-server
      - mongo
  reactive:
    container_name: reactive
    image: spring-6-reactive:0.0.1-SNAPSHOT
    expose:
      - 8082
    ports:
      - 8082:8082
    depends_on:
      - auth-server
  gateway:
    container_name: gateway
    image: spring-6-gateway:0.0.1-SNAPSHOT
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - auth-server
      - rest-mvc