apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rest-mvc
  name: rest-mvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-mvc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rest-mvc
    spec:
      containers:
      - image: spring-7-rest-mvc:0.0.1-SNAPSHOT
        name: spring-7-rest-mvc
        resources: {}
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "mysqllocal"
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:mysql://mysql:3306/restdb"
          - name: SERVER_PORT
            value: "8081"
          - name: SPRING_DOCKER_COMPOSE_ENABLED
            value: "false"
status: {}
