server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
      directory: logs
      pattern: '%h %l %u %t "%r" %s %b %D'
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: spring-6-rest-mvc
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/**
            - id: spring-6-reactive
              uri: http://localhost:8082
              predicates:
                - Path=/api/v2/**
            - id: spring-6-reactive-mongo
              uri: http://localhost:8083
              predicates:
                - Path=/api/v3/**

logging:
  level:
    root: error
    reactor.netty: trace
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.server.mvc: TRACE
    org.springframework.web.servlet.function: TRACE
    org.springframework.web.client: DEBUG